export default {
    locale: 'en',
    messages: {
        //公共
        'name': 'Name',
        'id': 'Id',

        'app.year':'year',
        'app.month':'month',
        'app.day':'day',

        'app.map': 'map',
        'app.list': 'list',
        'app.control': 'control',
        'app.scene': "scene",
        'app.strategy': "strategy",
        'app.device': 'Device',
        'app.domain': 'Domain',
        'app.open': 'on',
        'app.close': 'off',
        'app.update.time':'update time',
        'app.control.mode':'control mode',
        'app.automatic.time':'calibration',
        'app.click.automatic.time':'click calibration',

        'sysOperation.selected.device':'Selected Device',
        'app.device.operation':'device operation',

        'app.type':'type',
        'app.unit':'unit',
        'app.param':'param',
        'app.set.param':'set param',

        'app.input.minute':'input minute',

        'app.timetable':'Timetable',
        'app.sensor':'Sensor',
        'app.latlng':'LatLng',
        'app.time.range':'time range',
        'app.date.range':'date range',
        'app.date.error':'date error',
        'app.control.device':'control device',

        'app.work.day.select':'work day select',
        'app.chart':'chart',
        'app.set.brightness':'set brightness',
        'app.add.node':'add node',
        'app.please.add.timetable':'please add timetable',
        'app.add.strategy':'new strategy',
        'app.edit.strategy':'edit strategy',

        'app.screen':'screen',
        'app.lamp':'lamp',
        'app.sensor.type':'sensor type',
        'app.sensor.input.placeholder':'input sensor param',

        'app.sensor.noise': 'SENSOR NOISE',
        'app.sensor.pm25': 'SENSOR PM25',
        'app.sensor.pa': 'SENSOR PA',
        'app.sensor.humis': 'SENSOR HUMIS',
        'app.sensor.temps': 'SENSOR TEMPS',
        'app.sensor.winds': 'SENSOR WINDS',
        'app.sensor.winddir': 'SENSOR WINDDIR',
        'app.sensor.co': 'SENSOR CO',
        'app.sensor.o2': 'SENSOR O2',
        'app.sensor.ch4': 'SENSOR CH4',
        'app.sensor.ch2o': 'SENSOR CH2O',
        'app.sensor.lx': 'SENSOR LX',

        'app.input.numbers':'only input numbers',
        'app.exceed.maximum.support':'exceed maximum support',
        '':'',

        //按钮
        ' ': ' ',
        'button.add': 'Add',
        'button.edit': 'Edit',
        'button.delete': 'Delete',
        'button.confirm': 'Confirm',
        'button.cancel': 'Cancel',
        'button.module': 'Module Permissions',
        'button.import': 'Import',
        'button.set': 'Set',
        'button.finish': 'Finish',
        'button.modify':'Modify',
        'button.apply': 'apply',
        'button.close':'Close',
        'button.save':'Save',
        'button.add.gateway':'Add gateway',


        //用户中心
        'update.password':'Update password',
        'exit':'Exit',
        'sure.exit':'Are you sure to exit？',
        'new.password':'New password',
        'old.password':'Old password',

        //地图
        'map.location': 'Map Location',
        'map.lng':'Lng',
        'map.lat':'Lat',

        //设备
        'sysOperation.gateway':'Gateway',
        'sysOperation.lamp.control':'Single lamp controller',
        'sysOperation.pole':'Pole',
        'sysOperation.screen':'Screen',
        'sysOperation.sensor':'Sensor',
        'sysOperation.xes':'Xes',
        'sysOperation.charge':'Charge',

        //提示
        'app.not.found': 'Not Found',
        'illegal':'Illegal',
        'import.format.error':'Import Excel format is incorrect',        
        'add.Domain':'Please add domain first',
        'password.error':'The password can only be letters or number',
        'password.not.same':'The two password is not same', 
        'no.empty':'Can not be empty',        

        //删除弹框
        'delete.user': 'Are you sure to delete the seleted user ?',
        'delete.device': 'Are you sure to delete the seleted device ?',
        'delete.strategy':'Are you sure to delete the seleted strategy ?',
        'delete.group':'Are you sure to delete the seleted group ?',        

        //登录
        'login.form.title':'User Login',
        'login.button':'Login',
        'login.alert':"Error Incorrect username or password",

        //首页
        'app.title': 'Smart Light Manage System',
        'app.copyright':'Copyright © 2018 Shanghai Sansi Technology Co.,Ltd',
        'app.asset.manage': 'Asset Manage',
        'app.permission.manage': 'Permission',
        'app.system.operation': 'System Operate',
        'app.smart.light': 'Smart Lamp',
        'app.light': 'Smart Light',
        'app.report.manage': 'Report Manage',
        'app.mediaPublish': 'MediaPublish',
        'app.visualization': 'Visualization',
        'app.domain.manage': 'Domain Manage',

        //资产管理
        'asset.model': 'asset model',
        'asset.statistics': 'asset statistics',
        'asset.property': 'asset properties',
        'asset.type':'asset types',
        'asset.param':'default params',

        //域管理
        'domain.edit': 'domain edit',
        'domain.map': 'domain map',
        'domain.list': 'domain list',
        'domain.topology': 'topology',
        'domain.property': 'domain property',
        'domain.name':'Name',
        'domain.lng':'Lng',
        'domain.lat':'Lat',
        'domain.superior':'Superior',


        //权限管理
        'permission.username': 'UserName',
        'permission.lastLoginDate': 'Last Login Date',
        'permission.admin': 'Admin',
        'permission.deviceAdmin': 'Device admin',
        'permission.deviceOperator': 'Device operator',
        'permission.guest': 'Guest',
        'permission.addUser': 'Add User',
        'permission.userData': 'User Data',
        'permission.domain': 'Domain Manage',
        'permission.module': 'Module Manage',
        'permission.input.username': 'Please input username',
        'permission.input.domain': 'Please input domain',
        'permission.added': 'Added',
        'permission.lastname': 'Last Name',
        'permission.firstname': 'First Name',
        'permission.password': 'Password',
        'permission.repassword': 'Repassword',
        'permission.grade': 'Grade',

        //系统运维
        'sysOperation.device.config':'Device config',
        'sysOperation.whiteList':'WhiteList',
        'sysOperation.include':'Include',
        'sysOperation.devices':'devices',
        'sysOperation.input.device':'Input device name',
        'sysOperation.domain':'Domain',
        'sysOperation.type':'Type',
        'sysOperation.id':'Id',
        'sysOperation.dataOrigin':'Data origin',
        'sysOperation.dataOrigins':'data origins',
        'sysOperation.addDevice':'Add device',
        'sysOperation.importList':'Import list',
        'sysOperation.select':'Select the list file path',
        'sysOperation.cover':'Cover existing devices',
        'sysOperation.input.asset':'Please input asset name',
        'sysOperation.select.sensor':'Select sensor：',
        'sysOperation.label':'Label：', 
        'sysOperation.input.id':'Input id to add',

        'sysOperation.control.strategy':'Control Strategy',
        'sysOperation.service.monitoring':'Service Monitoring',
        'sysOperation.system.config':'System Config',
        'sysOperation.device.monitoring':'Device Monitoring',
        'sysOperation.device.maintenance':'Device Maintenance',
        'sysOperation.strategy.alert':'please input strategy name',
        'sysOperation.set.param':'please set param',
        'sysOperation.select.sensor':'please select sensor',
        'sysOperation.select.device':'please select device',
        'sysOperation.select.instruction':'please select instruction',

        'sysOperation.domain.edit.success':'domain edit success',
        'sysOperation.domain.add.success':'domain add success',
        'app.sunrise': 'sunrise',
        'app.sunrise.time.difference': 'sunrise time difference',
        'app.sunset': 'sunset',
        'app.sunset.time.difference': 'sunset time difference',

        'app.strategy.name.userd':'strategy name used',

        'app.strategy.platform':'Platform',

        //智慧路灯

        'app.map': 'map',
        'app.list': 'list',
        'app.control': 'control',
        'app.scene': "scene",
        'app.strategy': "strategy",

        'app.search.placeholder.name': 'Search name or domain',
        'app.search.list': 'Return',

        'app.device.control': 'device control',
        'app.environment-brightness-control': 'Auto',
        'app.manual.dimming': 'Manual Dimming',
        'app.strategy.dimming': 'Strategy Dimming',
        'app.group.dimming': 'Group Dimming',
        'app.switch': 'Switch',
        'app.preset': 'Preset',
        'app.zoom': 'Zoom',

        'app.schedule': 'Schedule',
        'app.led.control': 'led control',
        'app.online': 'online',
        'app.offline': 'offline',
        'app.charging': 'charging',
        'app.charging.fault': 'charging fault',

        'app.manual': 'Manual',

        'app.scene.order': 'scene order',
        'app.device.number': 'device number',
        'app.input.scene.name': 'input scene name',

        'app.time.strategy': 'time strategy',
        'app.sensor.strategy': 'sensor strategy',
        'app.latlng.strategy': 'latlng strategy',
        'app.input.strategy.name': 'input strategy name',
        'app.strategy.name': 'strategy name',
        'app.strategy.type': 'strategy type',
        'app.device.type': 'device type',
        'app.set.state': 'set state',
        'app.strategy.param': 'strategy param',
        'app.include.target.devices': 'include target devices',
        'app.strategy.group.name':'Group name',        
        'app.strategy.retryCount':'Retry count',
        'app.strategy.retryInterval':'Retry interval',
        'app.strategy.select.group':'Select group',
        'app.strategy.level':'Level',        

        'app.input.device.name':'input device name',
        'app.device.name': 'device name',
        'app.online.state': 'online state',
        'app.fault.state': 'fault state',
        'app.current.brightness':'current brightness',
        'app.brightness.mode':'brightness mode',
        'app.light.state':'light state',
        'app.switch.state':'switch state',
        'app.brightness':'brightness',
        'app.voltage':'voltage',
        'app.electric.current':'electric current',
        'app.power':'power',

        'app.device.switch':'device switch',
        'app.dimming': 'dimming',

        'app.remote':'remote',
        'app.auto':'auto',
        'app.comm.state':'communication state',
        'app.device.state':'device state',
        'app.dimming.mode':'device mode',

        'app.charge.state':'charge state',
        'app.total.charge':'total charge',
        'app.total.charge.time':'total charge time',
        'app.last.charge.time':'last charge time',

        //media
        'mediaPublish.playList': 'Play List',
        'mediaPublish.manage': 'Publish Manage',
        'mediaPublish.playType':'play type',
        'mediaPublish.addPlan':'Add plan',
        'mediaPublish.schemeName':'plan name',
        'mediaPublish.inputSchemeName':'please input plan name',
        'mediaPublish.resolution':'resolution',
        'mediaPublish.playPlan':'play plan',

        'mediaPublish.screenSize':'screen size',
        'mediaPublish.prompt':'Only letters, numbers, and underscores',
        'mediaPublish.isDeleteList':'Whether to delete the selected playlist',
        'mediaPublish.play':'play',
        'mediaPublish.enlarge':'enlarge',
        'mediaPublish.narrow':'narrow',
        'mediaPublish.savePlan':'Save',
        'mediaPublish.quit':'Quit',
        'mediaPublish.property':'Property',
        'mediaPublish.materialLib':'Material library',

        'mediaPublish.materialName':'name',
        'mediaPublish.textContent':'content',
        'mediaPublish.selectFont':'font type',
        'mediaPublish.fontColor':'font',
        'mediaPublish.fontSize':'font size',
        'mediaPublish.bgColor':'background',
        'mediaPublish.bgTransparent':'opacity',
        'mediaPublish.alignment':'alignment',
        'mediaPublish.playDuration':'duration',
        'mediaPublish.playSpeed':'speed',
        'mediaPublish.animation':'animation',
        'mediaPublish.wordSpacing':'wordSpacing',
        'mediaPublish.lineSpacing':'lineSpacing',

        'mediaPublish.reset':'Reset',
        'mediaPublish.apply':'Apply',
        'mediaPublish.check':'Please enter the correct parameters',
        'mediaPublish.repeatTimes':'repeat',
        'mediaPublish.scalingRatio':'scaling',
        'mediaPublish.fragmentRange':'range',
        'mediaPublish.to':'to',
        'mediaPublish.volume':'volume',
        'mediaPublish.number':'number',
        'mediaPublish.displayMethod':'mode',
        'mediaPublish.timeDirection':'direction',
        'mediaPublish.areaSet':'area',
        'mediaPublish.selectFormat':'format',
        'mediaPublish.singleLine':'singleLine',
        'mediaPublish.lastDate':'last date',
        'mediaPublish.lastTime':'last time',
        'mediaPublish.timeZone':'timeZone',
        'mediaPublish.dateFormat':'dateFormat',
        'mediaPublish.timeFormat':'timeFormat',
        'mediaPublish.playingMode':'mode',
        'mediaPublish.areaName':'area',
        'mediaPublish.areaWidth':'width',
        'mediaPublish.areaHeight':'height',
        'mediaPublish.x':'X',
        'mediaPublish.y':'Y',
        'mediaPublish.playEnd':'play end',
        'mediaPublish.planName':'plan name',
        'mediaPublish.inputPlanName':'please input plan name',
        'mediaPublish.startDate':'start date',
        'mediaPublish.endDate':'end date',
        'mediaPublish.startTime':'start time',
        'mediaPublish.endTime':'end time',
        'mediaPublish.weekday':'weekday',
        'mediaPublish.monday':'Mon',
        'mediaPublish.tuesday':'Tue',
        'mediaPublish.wednesday':'Wed',
        'mediaPublish.thursday':'Thu',
        'mediaPublish.friday':'Fri',
        'mediaPublish.saturday':'Sat',
        'mediaPublish.sunday':'Sun',
        'mediaPublish.selectWeekday':'please select weekday',
        'mediaPublish.uploadFile':'Upload file',
        'mediaPublish.addMaterial':'Add material',
        'mediaPublish.importMaterial':'import',
        'mediaPublish.selectFilePath':'select file',
        'mediaPublish.selectFilePrompt':'please select the corrent file',
        'mediaPublish.inputNamePrompt':'please input the name',
        'mediaPublish.uploading':'Uploading',
        'mediaPublish.uploadProgress':'progress',
        'mediaPublish.waiting':'Waiting',
        'mediaPublish.completed':'Completed',
        'mediaPublish.failed':'Failed',
        'mediaPublish.titleContent':'content',
        'mediaPublish.titleFont':'font family',
        'mediaPublish.titleSize':'font size',
        'mediaPublish.titleColor':'font color',
        'mediaPublish.timeScaleType':'time scale',
        'mediaPublish.timeScaleWidth':'width',
        'mediaPublish.timeScaleHeight':'height',
        'mediaPublish.timeScaleFont':'font family',
        'mediaPublish.timeScaleSize':'font size',
        'mediaPublish.timeScaleColor':'color',
        'mediaPublish.markingType':'marking type',
        'mediaPublish.markingWidth':'marking width',
        'mediaPublish.markingHeight':'marking height',
        'mediaPublish.markingFont':'marking font',
        'mediaPublish.markingSize':'marking size',
        'mediaPublish.markingColor':'marking color',
        'mediaPublish.dateFont':'date font',
        'mediaPublish.dateSize':'date size',
        'mediaPublish.dateColor':'date color',
        'mediaPublish.weekFont':'week font',
        'mediaPublish.weekSize':'week size',
        'mediaPublish.weekColor':'week color',
        'mediaPublish.hourHandColor':'hourHand color',
        'mediaPublish.minuteHandColor':'minuteHand color',
        'mediaPublish.secondHandColor':'secondHand color',
        'mediaPublish.timingPlay':'timing play',
        'mediaPublish.timingPlayPlan':'timing play plan',
        'mediaPublish.cyclePlayPlan':'cycle play plan',
        'mediaPublish.addPlayPlan':'add plan plan',
        'mediaPublish.pauseSign':'pause sign',
        'mediaPublish.addOrModifyPlan':'Add or modify timing play',
        'mediaPublish.timeInterval':'TimeInterval',
        'mediaPublish.specifyDate':'specify date',
        'mediaPublish.specifyTime':'specify time',

        //last
        'app.link.index': 'home',
        'app.link.config': 'config',
        'app.search': 'Search',
        'app.search.smartlight': 'smart-light',
        'app.search.camera': 'camera',
        'app.search.led': 'led',

        'app.screen.state': 'screen state',
        'app.environment.state': 'environment state',
        'app.camera.control': 'camera control',

        'app.led.status': 'led offline',
        'app.refresh': 'refresh',

        'app.publish': 'publish',
        'app.force': 'Focol',

        'app.work': 'Active',
        'app.call': 'call',
        'app.plus': 'plus',
        'app.minus': 'minus',
        'app.left-top': 'left top',
        'app.top': 'top',
        'app.right-top': 'right top',
        'app.left': 'left',
        'app.center': 'center',
        'app.right': 'right',
        'app.left-bottom': 'left bottom',
        'app.bottom': 'bottom',
        'app.right-bottom': 'right bottom',
        'app.screen.refresh': 'click refresh',

        'app.width': 'Width',
        'app.height': 'Heigth',
        'app.version': 'Version',
        'app.brightness_mode': 'Brightness Mode',
        'app.brightness': 'Brightness',
        'app.sys_fault': 'System Fault',
        'app.vram_fault': 'Vram Fault',
        'app.disp_module_fault': 'Display Module Fault',
        'app.disp_module_power_fault': 'Display Module Power Fault',
        'app.single_pixel_tube_fault': 'Single Pixel Tube Fault',
        'app.detection_sys_fault': 'Detection System Fault',
        'app.ac_fault': 'AC Fault',
        'app.lightning_arrester_fault': 'Lightning Arrester Fault',
        'app.photosensor_fault': 'Photosensitive Component Fault',
        'app.abnormal_temperature_fault': 'Abnormal Temperature Fault',
        'app.door_switch_fault': 'Door Switch Fault',
        'app.fault': 'Fault',
        'app.fault_info': 'Fault Information',

        'app.normal': 'Normal',
        'app.abnormal': 'Abnormal',

        'app.temperature': 'Temperature',
        'app.humidity': 'Humidity',
        'app.air-pressure': 'Air Pressure',
        'app.noise': 'Noise',
        'app.wind-speed': 'Wind Speed',
        'app.wind-direction': 'Wind Direction',
        'app.pm25': 'PM2.5',
        'app.o2': 'O2',
        'app.co': 'CO',

        'app.Static': 'Static',
        'app.N': 'N',
        'app.NE': 'NE',
        'app.E': 'E',
        'app.SE': 'SE',
        'app.S': 'S',
        'app.SW': 'SW',
        'app.W': 'W',
        'app.NW': 'NW',

        'app.screen.content': 'Uploading...',
        'app.screen.content2': 'This could take a while',
        'app.confirm': 'OK',

        'app.alarm': 'Alarm',
        'app.name': 'name',
        'app.type': 'type',
        'app.date': 'time',

        'manage.title': 'StarRiver Manage',

        'manage.link.gateway': 'Gateway',
        'manage.link.whiteList': 'WhiteList',
        'manage.link.camera': 'Camera',
        'manage.link.smartLight': 'Smart Light',
        'manage.link.screen': 'Screen',
        'manage.link.playList': 'PlayList',
        'manage.link.rfid': 'RFID',

        'panel.info': 'No relevant data!',
        'manage.name': 'Name',

        'manage.screen.table.esn': 'ESN',
        'manage.screen.table.name': 'Name',
        'manage.screen.table.domain': 'Domain',
        'manage.smartlight.table.name': 'Name',
        'manage.smartlight.table.screen': 'Screen',
        'manage.smartlight.table.camera': 'Camera',
        'manage.smartlight.table.rfid': 'RFID',
        'manage.smartlight.table.longitude': 'Longitude',
        'manage.smartlight.table.langitude': 'Langitude',

        'manage.popup.pleaseSelect': 'please select',
        'manage.popup.confirmDelete': 'confirm delete',
        'manage.popup.tips': 'Tips',
        'manage.popup.smartlight.addSmartlight': 'Add Smart Light',
        'manage.popup.smartlight.editSmartlight': 'Edit Smart Light',
        'manage.popup.smartlight.pole': 'Pole',
        'manage.popup.smartlight.screen': 'Screen',
        'manage.popup.smartlight.camera': 'Camera',
        'manage.popup.smartlight.rfid': 'RFID',
        'manage.popup.screen.addScreen': 'Add Screen',
        'manage.popup.screen.editScreen': 'Edit Screen',
        'manage.popup.screen.esn': 'ESN',
        'manage.popup.screen.name': 'Name',
        'manage.popup.screen.domain': 'Domain',

        'manage.playlist.time': 'Modify Time',
        'manage.playlist.add': 'Add Playlist',
        'manage.playlist.browse': 'Select File',

        'manage.camera.ip': 'IP',
        'manage.camera.rtsp': 'RTSP Port',
        'manage.camera.http': 'HTTP Port',
        'manage.camera.username': 'Username',
        'manage.camera.password': 'Password',
        'manage.camera.channel': 'Channel',
        'manage.camera.add': 'Add Camera',
        'manage.camera.edit': 'Edit Camera',

        'manage.rfid.esn': 'ESN',
        'manage.rfid.name': 'Name',
        'manage.rfid.domain': 'Domain',
        'manage.rfid.add': 'Add RFID',
        'manage.rfid.edit': 'Edit RFID',
    }
}