export default  {
    locale:'en',
    messages:{
        //按钮
        ' ':' ',
        'button.add': 'Add',
        'button.edit': 'Edit',
        'button.delete': 'Delete',
        'button.confirm': 'Confirm',
        'button.cancel': 'Cancel',
        'button.module':'Module Permissions',
        'button.import': 'Import',        
        
        //地图
        'map.location':'Map Location',

        //提示
        'app.not.found':'Not Found',
        
        //删除弹框
        'delete.user':'Are you sure to delete the seleted user？',

        //首页
        'app.title':'Smart Light Manage System',
        'app.asset.manage':'Asset Manage',
        'app.permission.manage':'Permission',
        'app.system.operation':'System Operate',
        'app.smart.light':'Smart Lamp',
        'app.light':'Smart Light',
        'app.report.manage':'Report Manage',
        'app.mediaPublish':'MediaPublish',
        'app.visualization':'Visualization',
        'app.domain.manage':'Domain Manage',

        //资产管理
        'asset.model': 'asset model',
        'asset.statistics': 'asset statistics',

        //权限管理
        'permission.username':'UserName',
        'permission.lastLoginDate':'Last Login Date',
        'permission.admin':'Admin',
        'permission.deviceAdmin':'Device admin',
        'permission.deviceOperator':'Device operator',
        'permission.guest':'Guest',
        'permission.addUser':'Add User',
        'permission.userData':'User Data',
        'permission.domain':'Domain Manage',
        'permission.module':'Module Manage',
        'permission.input.username':'Please input username', 
        'permission.input.domain':'Please input domain', 
        'permission.added':'Added',
        'permission.lastname':'Last Name',
        'permission.firstname':'First Name',
        'permission.password':'Password',
        'permission.repassword':'Repassword',  
        'permission.grade':'Grade',
        
        //系统运维
        'sysOperation.selected.device':'Selected Device',
        'sysOperation.whiteList':'WhiteList',
        'sysOperation.include':'Include',
        'sysOperation.devices':'devices',
        'sysOperation.input.device':'Input device name',
        'sysOperation.domain':'Domain',
        'sysOperation.device':'DeviceName',
        'sysOperation.type':'Type',
        'sysOperation.id':'Id',
        'sysOperation.lng':'Lng',
        'sysOperation.lat':'Lat', 
        'sysOperation.dataOrigin':'Data origin',
        'sysOperation.dataOrigins':'data origins',

        //智慧路灯
        'app.map': 'map',
        'app.list': 'list',
        'app.control': 'control',
        'app.scene': "scene",
        'app.strategy': "strategy",
        
        'app.search.placeholder.name': 'Search name or domain',
        'app.search.list': 'Return',
        'app.device': 'Device',
        'app.domain': 'Domain',
        'app.open': 'on',
        'app.close': 'off',
        'app.device.control': 'device control',
        'app.apply': 'apply',
        'app.environment-brightness-control': 'Auto',
        'app.manual.dimming': 'Manual Dimming',
        'app.strategy.dimming': 'Strategy Dimming',
        'app.group.dimming': 'Group Dimming',
        'app.switch': 'Switch',
        'app.preset': 'Preset',
        'app.zoom': 'Zoom',

        'app.schedule': 'Schedule',
        'app.led.control': 'led control',
        'app.online': 'online',
        'app.offline': 'offline',
        'app.charging': 'charging',
        'app.charging.fault': 'charging fault',

        'app.manual':'Manual',

        'app.scene.order': 'scene order',
        'app.device.number': 'device number',
        'app.input.scene.name': 'input scene name',

        //last
        'app.link.index': 'home',
        'app.link.config': 'config',
        'app.search': 'Search',
        'app.search.smartlight': 'smart-light',
        'app.search.camera': 'camera',
        'app.search.led': 'led',

        'app.screen.state': 'screen state',
        'app.environment.state': 'environment state',
        'app.camera.control': 'camera control',
       
        'app.led.status': 'led offline',
        'app.refresh': 'refresh',

        'app.publish': 'publish',
        'app.force': 'Focol',

        'app.work': 'Active',
        'app.call': 'call',
        'app.plus': 'plus',
        'app.minus': 'minus',
        'app.left-top': 'left top',
        'app.top': 'top',
        'app.right-top': 'right top',
        'app.left': 'left',
        'app.center': 'center',
        'app.right': 'right',
        'app.left-bottom': 'left bottom',
        'app.bottom': 'bottom',
        'app.right-bottom': 'right bottom',
        'app.screen.refresh': 'click refresh',

        'app.width': 'Width',
        'app.height': 'Heigth',
        'app.version': 'Version',
        'app.brightness_mode': 'Brightness Mode',
        'app.brightness': 'Brightness',
        'app.sys_fault': 'System Fault',
        'app.vram_fault': 'Vram Fault',
        'app.disp_module_fault': 'Display Module Fault',
        'app.disp_module_power_fault': 'Display Module Power Fault',
        'app.single_pixel_tube_fault': 'Single Pixel Tube Fault',
        'app.detection_sys_fault': 'Detection System Fault',
        'app.ac_fault': 'AC Fault',
        'app.lightning_arrester_fault': 'Lightning Arrester Fault',
        'app.photosensor_fault': 'Photosensitive Component Fault',
        'app.abnormal_temperature_fault': 'Abnormal Temperature Fault',
        'app.door_switch_fault': 'Door Switch Fault',
        'app.fault': 'Fault',
        'app.fault_info': 'Fault Information',

        'app.normal': 'Normal',
        'app.abnormal': 'Abnormal',

        'app.temperature': 'Temperature',
        'app.humidity': 'Humidity',
        'app.air-pressure': 'Air Pressure',
        'app.noise': 'Noise',
        'app.wind-speed': 'Wind Speed',
        'app.wind-direction': 'Wind Direction',
        'app.pm25': 'PM2.5',
        'app.o2': 'O2',
        'app.co': 'CO',

        'app.Static': 'Static',
        'app.N': 'N',
        'app.NE': 'NE',
        'app.E': 'E',
        'app.SE': 'SE',
        'app.S': 'S',
        'app.SW': 'SW',
        'app.W': 'W',
        'app.NW': 'NW',

        'app.screen.content':'Uploading...',
        'app.screen.content2':'This could take a while',
        'app.confirm':'OK',

        'app.alarm':'Alarm',
        'app.name':'name',
        'app.type':'type',
        'app.date':'time',

        'manage.title':'StarRiver Manage',

        'manage.link.gateway': 'Gateway',
        'manage.link.whiteList': 'WhiteList',
        'manage.link.camera': 'Camera',
        'manage.link.smartLight': 'Smart Light',
        'manage.link.screen': 'Screen',
        'manage.link.playList':'PlayList',
        'manage.link.rfid':'RFID',

        'panel.info': 'No relevant data!',
        'manage.name':'Name',

        'manage.screen.table.esn': 'ESN',
        'manage.screen.table.name': 'Name',
        'manage.screen.table.domain': 'Domain',
        'manage.smartlight.table.name': 'Name',
        'manage.smartlight.table.screen': 'Screen',
        'manage.smartlight.table.camera': 'Camera',
        'manage.smartlight.table.rfid': 'RFID',
        'manage.smartlight.table.longitude': 'Longitude',
        'manage.smartlight.table.langitude': 'Langitude',

        'manage.popup.pleaseSelect': 'please select',
        'manage.popup.confirmDelete': 'confirm delete',
        'manage.popup.tips': 'Tips',
        'manage.popup.smartlight.addSmartlight': 'Add Smart Light',
        'manage.popup.smartlight.editSmartlight': 'Edit Smart Light',
        'manage.popup.smartlight.pole': 'Pole',
        'manage.popup.smartlight.screen': 'Screen',
        'manage.popup.smartlight.camera': 'Camera',
        'manage.popup.smartlight.rfid': 'RFID',
        'manage.popup.screen.addScreen': 'Add Screen',
        'manage.popup.screen.editScreen': 'Edit Screen',
        'manage.popup.screen.esn': 'ESN',
        'manage.popup.screen.name': 'Name',
        'manage.popup.screen.domain': 'Domain',

        'manage.playlist.time':'Modify Time',
        'manage.playlist.add':'Add Playlist',
        'manage.playlist.browse':'Select File',

        'manage.camera.ip':'IP',
        'manage.camera.rtsp':'RTSP Port',
        'manage.camera.http':'HTTP Port',
        'manage.camera.username':'Username',
        'manage.camera.password':'Password',
        'manage.camera.channel':'Channel',
        'manage.camera.add':'Add Camera',
        'manage.camera.edit':'Edit Camera',

        'manage.rfid.esn': 'ESN',
        'manage.rfid.name': 'Name',
        'manage.rfid.domain': 'Domain',
        'manage.rfid.add':'Add RFID',
        'manage.rfid.edit':'Edit RFID',
    }
}