export default {
  locale: 'zh',
  messages: {
    //公共
    'name': '名称',
    'id': '编号',

    'app.year': '年',
    'app.month': '月',
    'app.day': '日',

    'app.map': '地图',
    'app.list': '列表',
    'app.control': '控制',
    'app.scene': '场景',
    'app.strategy': '策略',
    'app.device': '设备',
    'app.domain': '域',
    'app.open': '开',
    'app.close': '关',
    'app.update.time': '更新时间',
    'app.control.mode': '控制模式',
    'app.automatic.time': '校时',
    'app.click.automatic.time': '点击校时',

    'sysOperation.selected.device': '选中设备',
    'app.device.operation': '设备操作',

    'app.type': '类别',
    'app.unit': '单位',
    'app.param': '当前参数',
    'app.set.param': '设置参数',

    'app.input.minute': '输入分钟数',
    '': '',

    'app.timetable': '时间表',
    'app.sensor': '传感器',
    'app.latlng': '经纬度',
    'app.time.range': '时间范围',
    'app.date.range': '日期范围',
    'app.date.error': '日期错误',
    'app.control.device': '控制设备',

    'app.work.day.select': '工作日选择',
    'app.chart': '图表',
    'app.set.brightness': '设置亮度',
    'app.add.node': '添加节点',
    'app.please.add.timetable': '请添加时间亮度表',
    'app.add.strategy': '新建策略',
    'app.edit.strategy': '修改策略',

    'app.screen': '显示屏',
    'app.lamp': '灯',
    'app.sensor.type': '传感器类型',
    'app.sensor.input.placeholder': '输入传感器参数',

    'app.sensor.noise': '噪声传感器',
    'app.sensor.pm25': 'PM2.5 传感器',
    'app.sensor.pa': '大气压传感器',
    'app.sensor.humis': '湿度传感器',
    'app.sensor.temps': '温度传感器',
    'app.sensor.winds': '风速传感器',
    'app.sensor.winddir': '风向传感器',
    'app.sensor.co': '一氧化碳传感器',
    'app.sensor.o2': '氧气传感器',
    'app.sensor.ch4': '甲烷传感器',
    'app.sensor.ch2o': '甲醛传感器',
    'app.sensor.lx': '照度传感器',

    'app.input.numbers': '仅能输入数字',
    'app.exceed.maximum.support': '超过最大支持',

    'app.group': '组',
    'app.statistics': '统计',

    'app.resolution': '屏分辨率',
    'app.work.state': '工作状态',

    //按钮
    ' ': ' ',
    'button.add': '添加',
    'button.edit': '编辑',
    'button.delete': '删除',
    'button.confirm': '确认',
    'button.nextStep': '下一步',
    'button.lastStep': '上一步',
    'button.import': '导入',
    'button.cancel': '取消',
    'button.set': '设定',
    'button.finish': '完成',
    'button.modify': '修改',
    'button.apply': '应用',
    'button.close': '关闭',
    'button.save': '保存',
    'button.add.gateway': '添加网关',
    'button.start': '启用',
    'button.pause': '暂停',
    'button.ignore': '忽略',
    'button.solve': '解决',
    'button.to.fault': '转故障',
    'button.acceptable': '可接受',
    'button.hangUp': '挂起',

    //用户中心
    'update.password': '修改密码',
    'exit': '退出管理系统',
    'sure.exit': '确认退出？',
    'new.password': '新密码',
    'old.password': '旧密码',

    //地图
    'map.location': '地图位置',
    'map.lng': '经度',
    'map.lat': '纬度',
    'map.device.tip': '件设备',

    //设备
    'sysOperation.gateway': '网关',
    'sysOperation.lamp.control': '单灯控制器',
    'sysOperation.pole': '灯杆',
    'sysOperation.screen': '显示屏',
    'sysOperation.sensor': '传感器',
    'sysOperation.xes': '数据采集仪',
    'sysOperation.charge': '充电桩',

    //提示
    'app.not.found': '没有找到结果',
    'illegal': '不合法',
    'import.format.error': '导入Excel格式有误',
    'add.Domain': '请添加域',
    'password.error': '密码只能为字母或数字',
    'password.not.same': '两次密码不一致',
    'no.empty': '不能为空',

    //删除弹框
    'delete.user': '是否删除选中用户？',
    'delete.device': '是否删除选中设备？',
    'delete.strategy': '是否删除选中策略？',
    'delete.group': '是否删除选中组？',

    //登录
    'login.form.title': '用户登录',
    'login.button': '登录',
    'login.alert': '用户名或密码错误',

    //首页
    'app.title': '智慧路灯管理系统',
    'app.copyright': 'Copyright © 2018 上海三思电子工程有限公司',
    'app.asset.manage': '资产管理',
    'app.permission.manage': '权限管理',
    'app.system.operation': '系统运维',
    'app.smart.light': '智慧路灯',
    'app.light': '智能照明',
    'app.report.manage': '报表管理',
    'app.mediaPublish': '媒体发布',
    'app.visualization': '可视化',
    'app.domain.manage': '域管理',

    //资产管理
    'asset.model': '资产管理',
    'asset.statistics': '资产统计',
    'asset.property': '设备属性',
    'asset.equipmentModal': '设备型号',
    'asset.type': '设备类别',
    'asset.param': '默认参数',

    //域管理
    'domain.edit': '域编辑',
    'domain.map': '地图预览',
    'domain.list': '列表模式',
    'domain.topology': '拓扑图',
    'domain.property': '域属性',
    'domain.name': '域名称',
    'domain.lng': '经度',
    'domain.lat': '纬度',
    'domain.superior': '上级域',
    //权限管理
    'permission.username': '用户名称',
    'permission.lastLoginDate': '最后登录时间',
    'permission.admin': '系统管理员',
    'permission.deviceAdmin': '设备管理员',
    'permission.deviceOperator': '设备操作员',
    'permission.guest': '访客',
    'permission.addUser': '添加用户',
    'permission.userData': '用户资料',
    'permission.domain': '域权限',
    'permission.module': '模块权限',
    'permission.input.username': '请输入用户名称',
    'permission.input.domain': '请输入域名称',
    'permission.added': '已添加',
    'permission.lastname': '姓氏',
    'permission.firstname': '名字',
    'permission.password': '密码',
    'permission.repassword': '重复密码',
    'permission.grade': '用户等级',

    //系统运维
    'sysOperation.device.config': '设备配置',
    'sysOperation.whiteList': '白名单',
    'sysOperation.include': '包含',
    'sysOperation.devices': '个设备',
    'sysOperation.input.device': '输入设备名称',
    'sysOperation.domain': '域',
    'sysOperation.type': '型号',
    'sysOperation.id': '设备编号',
    'sysOperation.dataOrigin': '数据源',
    'sysOperation.dataOrigins': '个数据源',
    'sysOperation.addDevice': '添加设备',
    'sysOperation.importList': '导入列表',
    'sysOperation.deviceReplace': '更换设备',
    'sysOperation.deviceUpgrade': '升级',
    'sysOperation.select': '选择列表文件路径',
    'sysOperation.cover': '覆盖已有设备',
    'sysOperation.input.asset': '请输入素材名称',
    'sysOperation.select.sensor': '选择传感器：',
    'sysOperation.label': '标签：',
    'sysOperation.input.id': '输入编号添加',

    'sysOperation.control.strategy': '控制策略',
    'sysOperation.service.monitoring': '服务监控',
    'sysOperation.system.config': '系统配置',
    'sysOperation.device.monitoring': '设备监控',
    'sysOperation.device.maintenance': '设备维护',
    'sysOperation.strategy.alert': '请添加策略名称',
    'sysOperation.set.param': '请设置参数',
    'sysOperation.select.device': '请选择设备',
    'sysOperation.select.instruction': '请选择指令',

    'sysOperation.domain.edit.success': '编辑域成功',
    'sysOperation.domain.add.success': '添加域成功',
    'app.sunrise': '日出',
    'app.sunrise.time.difference': '日出时间差',
    'app.sunset': '日落',
    'app.sunset.time.difference': '日落时间差',
    'app.strategy.name.used': '策略名已使用',
    '': '',

    'app.strategy.platform': '平台',
    'app.select.group': '选中组',
    'app.select.strategy': '选中策略',
    'app.strategy.property': '调整参数',
    'app.strategy.devices': '包含设备',
    'app.strategy.select.devices': '选择设备',
    'app.strategy.identifying': '标识',
    'app.time.difference': '时间差',

    //设备维护
    'sysOperation.dviceNum': '编号',
    'sysOperation.dviceName': '名称',
    'sysOperation.domainName': '域',
    //故障管理
    'sysOperation.fault.manage': '故障管理',
    'sysOperation.alarm.type': '告警类别',
    'sysOperation.alarm.param': '告警参数',
    'sysOperation.fault.param': '故障参数',
    'sysOperation.alarm.device.model': '设备模型',
    'sysOperation.alarm.level': '告警级别',
    'sysOperation.fault.level': '故障级别',
    'sysOperation.alarm.threshold': '阈值',
    'sysOperation.alarm.test.value': '检测值',
    'sysOperation.alarm.time': '告警时间',
    'sysOperation.fault.time': '故障时间',
    'sysOperation.alarm.status': '告警状态',
    'sysOperation.fault.status': '故障状态',
    'sysOperation.alarm.person': '处理人',
    'sysOperation.alarm.handle.time': '处理时间',
    'sysOperation.fault.id': '故障编号',

    'sysOperation.alarm.statistical.info': '告警统计信息',
    'sysOperation.fault.statistical.info': '故障统计信息',

    'sysOperation.count.deadly': '致命数',
    'sysOperation.count.serious': '严重数',
    'sysOperation.count.general': '一般数',
    'sysOperation.count.hint': '提示数',
    'sysOperation.noCount': '未读取',

    //智慧路灯
    'app.search.placeholder.name': '搜索名称或域',
    'app.search.list': '返回',
    'app.device.control': '设备控制',
    'app.environment-brightness-control': '环境亮度控制',
    'app.manual.dimming': '手动调光',
    'app.strategy.dimming': '策略调光',
    'app.group.dimming': '组调光',
    'app.switch': '切换',
    'app.preset': '预置',
    'app.zoom': '变焦',

    'app.schedule': '时间表',
    'app.led.control': '显示屏控制',
    'app.online': '在线',
    'app.offline': '离线',
    'app.charging': '充电中。。。',
    'app.charging.fault': '充电故障',

    'app.manual': '手动',

    'app.scene.order': '场景序号',
    'app.device.number': '设备数量',
    'app.input.scene.name': '输入场景名称',

    'app.time.strategy': '时间策略',
    'app.sensor.strategy': '传感器策略',
    'app.latlng.strategy': '经纬度策略',
    'app.input.strategy.name': '输入策略名称',
    'app.input.strategys.name': '输入组和策略名称',
    'app.strategy.name': '策略名称',
    'app.strategy.type': '策略类型',
    'app.device.type': '设备种类',
    'app.set.state': '设定状态',
    'app.strategy.param': '策略参数',
    'app.include.target.devices': '包含目标设备',
    'app.strategy.group.name': '组名称',
    'app.strategy.retryNumber': '重试次数',
    'app.strategy.retryInterval': '重试间隔',
    'app.strategy.select.group': '选择组',
    'app.strategy.level': '策略级别',
    'app.strategy.state': '状态',
    'app.task.create.time': '创建时间',
    'app.task.execute.time': '执行时间',
    'app.task.execute.result': '执行结果',
    'app.task.record': '任务记录',
    'app.status.started': '已启用',
    'app.status.paused': '已停用',
    'app.status.start': '是否启用',
    'app.status.pause': '是否停用',

    'app.input.device.name': '请输入设备名称',
    'app.device.name': '设备名称',
    'app.online.state': '在线状态',
    'app.fault.state': '故障状态',
    'app.current.brightness': '当前亮度',
    'app.brightness.mode': '亮度模式',
    'app.light.state': '灯状态',
    'app.switch.state': '开关状态',
    'app.brightness': '亮度',
    'app.voltage': '电压',
    'app.electric.current': '电流',
    'app.power': '功率',

    'app.device.switch': '设备开关',
    'app.dimming': '调光',

    'app.remote': '远程',
    'app.auto': '自动',
    'app.comm.state': '通信状态',
    'app.device.state': '设备状态',
    'app.dimming.mode': '设备模式',

    'app.charge.state': '充电状态',
    'app.total.charge': '总充电量',
    'app.total.charge.time': '总充电时长',
    'app.last.charge.time': '最后一次充电时间',

    //多媒体
    'mediaPublish.playList': '播放列表',
    'mediaPublish.manage': '发布管理',
    'mediaPublish.playType': '播放类型',
    'mediaPublish.addPlan': '添加方案',
    'mediaPublish.schemeName': '方案名称',
    'mediaPublish.inputSchemeName': '输入方案名称',
    'mediaPublish.resolution': '分辨率',
    'mediaPublish.playPlan': '播放方案',
    'mediaPublish.screenSize': '屏幕尺寸',
    'mediaPublish.prompt': '仅能输入字母、数字、下划线',
    'mediaPublish.isDeleteList': '是否删除选中播放列表',
    'mediaPublish.play': '播放',
    'mediaPublish.enlarge': '放大',
    'mediaPublish.narrow': '缩小',
    'mediaPublish.savePlan': '保存计划',
    'mediaPublish.quit': '退出',
    'mediaPublish.property': '属性',
    'mediaPublish.materialLib': '素材库',

    'mediaPublish.materialName': '素材名称',
    'mediaPublish.textContent': '文本内容',
    'mediaPublish.selectFont': '选择字体',
    'mediaPublish.fontColor': '字体颜色',
    'mediaPublish.fontSize': '字体大小',
    'mediaPublish.bgColor': '背景颜色',
    'mediaPublish.bgTransparent': '背景透明',
    'mediaPublish.alignment': '对齐方式',
    'mediaPublish.playDuration': '播放时长',
    'mediaPublish.playSpeed': '播放速度',
    'mediaPublish.animation': '动画效果',
    'mediaPublish.wordSpacing': '字间距',
    'mediaPublish.lineSpacing': '行间距',

    'mediaPublish.reset': '重置',
    'mediaPublish.apply': '应用',
    'mediaPublish.check': '请输入正确参数',
    'mediaPublish.repeatTimes': '播放次数',
    'mediaPublish.scalingRatio': '缩放比例',
    'mediaPublish.fragmentRange': '片段范围',
    'mediaPublish.to': '至',
    'mediaPublish.volume': '音量',
    'mediaPublish.number': '次',
    'mediaPublish.displayMethod': '显示方式',
    'mediaPublish.timeDirection': '计时方式',
    'mediaPublish.areaSet': '区域设置',
    'mediaPublish.selectFormat': '选择格式',
    'mediaPublish.singleLine': '单行显示',
    'mediaPublish.lastDate': '截止日期',
    'mediaPublish.lastTime': '截止时间',
    'mediaPublish.timeZone': '时区',
    'mediaPublish.dateFormat': '日期格式',
    'mediaPublish.timeFormat': '时间格式',
    'mediaPublish.playingMode': '播放方式',
    'mediaPublish.areaName': '区域名称',
    'mediaPublish.areaWidth': '区域宽度',
    'mediaPublish.areaHeight': '区域高度',
    'mediaPublish.x': 'X轴坐标',
    'mediaPublish.y': 'Y轴坐标',
    'mediaPublish.playEnd': '播放结束',
    'mediaPublish.planName': '计划名称',
    'mediaPublish.inputPlanName': '请输入名称',
    'mediaPublish.startDate': '开始日期',
    'mediaPublish.endDate': '结束日期',
    'mediaPublish.startTime': '开始时间',
    'mediaPublish.endTime': '结束时间',
    'mediaPublish.weekday': '工作日',
    'mediaPublish.monday': '周一',
    'mediaPublish.tuesday': '周二',
    'mediaPublish.wednesday': '周三',
    'mediaPublish.thursday': '周四',
    'mediaPublish.friday': '周五',
    'mediaPublish.saturday': '周六',
    'mediaPublish.sunday': '周日',
    'mediaPublish.selectWeekday': '请选择工作日',
    'mediaPublish.uploadFile': '上传文件',
    'mediaPublish.addMaterial': '添加素材',
    'mediaPublish.importMaterial': '导入素材',
    'mediaPublish.selectFilePath': '选择列表文件路径',
    'mediaPublish.selectFilePrompt': '请选择文件',
    'mediaPublish.inputNamePrompt': '请输入名称',
    'mediaPublish.uploading': '正在上传',
    'mediaPublish.uploadProgress': '上传进度',
    'mediaPublish.waiting': '待上传',
    'mediaPublish.completed': '已完成',
    'mediaPublish.failed': '失败',
    'mediaPublish.titleContent': '标题内容',
    'mediaPublish.titleFont': '标题字体',
    'mediaPublish.titleSize': '标题大小',
    'mediaPublish.titleColor': '标题颜色',
    'mediaPublish.timeScaleType': '时标类型',
    'mediaPublish.timeScaleWidth': '时标宽度',
    'mediaPublish.timeScaleHeight': '时标高度',
    'mediaPublish.timeScaleFont': '时标字体',
    'mediaPublish.timeScaleSize': '时标大小',
    'mediaPublish.timeScaleColor': '时标颜色',
    'mediaPublish.markingType': '分标类型',
    'mediaPublish.markingWidth': '分标宽度',
    'mediaPublish.markingHeight': '分标高度',
    'mediaPublish.markingFont': '分标字体',
    'mediaPublish.markingSize': '分标大小',
    'mediaPublish.markingColor': '分标颜色',
    'mediaPublish.dateFont': '日期字体',
    'mediaPublish.dateSize': '日期大小',
    'mediaPublish.dateColor': '日期颜色',
    'mediaPublish.weekFont': '星期字体',
    'mediaPublish.weekSize': '星期大小',
    'mediaPublish.weekColor': '星期颜色',
    'mediaPublish.hourHandColor': '时针颜色',
    'mediaPublish.minuteHandColor': '分针颜色',
    'mediaPublish.secondHandColor': '秒针颜色',
    'mediaPublish.timingPlay': '定时插播',
    'mediaPublish.timingPlayPlan': '定时插播计划',
    'mediaPublish.cyclePlayPlan': '周期插播计划',
    'mediaPublish.addPlayPlan': '播放计划新建',
    'mediaPublish.pauseSign': '暂停标志',
    'mediaPublish.addOrEditPlan': '添加/修改插播计划',
    'mediaPublish.timeInterval': '时间间隔',
    'mediaPublish.specifyDate': '指定日期',
    'mediaPublish.specifyTime': '指定时间',

    'mediaPublish.area.alert': '请选择区域',

    //以前的
    'app.link.index': '首页',
    'app.link.config': '配置',
    'app.search': '搜索',
    'app.search.smartlight': '智慧路灯',
    'app.search.camera': '摄像头',
    'app.search.led': '屏',
    'app.screen.state': '屏状态',
    'app.environment.state': '环境状态',
    'app.camera.control': '摄像头控制',

    'app.led.status': '显示屏离线',
    'app.refresh': '刷新',

    'app.publish': '发布',
    'app.force': '焦距',

    'app.work': '激活',
    'app.call': '调用',
    'app.plus': '加',
    'app.minus': '减',
    'app.left-top': '左上',
    'app.top': '上',
    'app.right-top': '右上',
    'app.left': '左',
    'app.center': '中',
    'app.right': '右',
    'app.left-bottom': '左下',
    'app.bottom': '下',
    'app.right-bottom': '右下',
    'app.screen.refresh': '单击刷新',

    'app.width': '宽度',
    'app.height': '高度',
    'app.version': '版本号',
    'app.brightness_mode': '亮度模式',
    'app.sys_fault': '系统故障',
    'app.vram_fault': 'VRAM故障',
    'app.disp_module_fault': '显示模组故障',
    'app.disp_module_power_fault': '显示模组电源故障',
    'app.single_pixel_tube_fault': '单像素管故障',
    'app.detection_sys_fault': '检测系统故障',
    'app.ac_fault': '交流电故障',
    'app.lightning_arrester_fault': '防雷器故障',
    'app.photosensor_fault': '光敏部件故障',
    'app.abnormal_temperature_fault': '温度异常故障',
    'app.door_switch_fault': '门开关故障',
    'app.fault': '故障',
    'app.fault_info': '屏故障信息',

    'app.normal': '正常',
    'app.abnormal': '异常',

    'app.temperature': '环境温度',
    'app.humidity': '环境湿度',
    'app.air-pressure': '气压',
    'app.noise': '噪音',
    'app.wind-speed': '风速',
    'app.wind-direction': '风向',
    'app.pm25': 'PM2.5',
    'app.o2': 'O2',
    'app.co': 'CO',

    'app.Static': '无风',
    'app.N': '北风',
    'app.NE': '东北风',
    'app.E': '东风',
    'app.SE': '东南风',
    'app.S': '南风',
    'app.SW': '西南风',
    'app.W': '西风',
    'app.NW': '西北风',

    'app.screen.content': '上传播放列表需要一段时间，',
    'app.screen.content2': '请您耐心等待，请稍后查看。',
    'app.confirm': '确定',

    'app.alarm': '警报',
    'app.name': '名称',
    'app.date': '时间',

    'manage.title': 'StarRiver 管理',

    'manage.link.gateway': '网关',

    'manage.link.whiteList': '白名单',
    'manage.link.camera': '摄像头',
    'manage.link.smartLight': '智慧路灯',
    'manage.link.screen': '屏',
    'manage.link.rfid': 'RFID',

    'panel.info': '无相关数据！',
    'manage.name': '名称',

    'manage.screen.table.esn': 'ESN',
    'manage.screen.table.name': '名称',
    'manage.screen.table.domain': '域',
    'manage.smartlight.table.name': '名称',
    'manage.smartlight.table.screen': '显示屏',
    'manage.smartlight.table.camera': '摄像头',
    'manage.smartlight.table.rfid': 'RFID',
    'manage.smartlight.table.longitude': '经度',
    'manage.smartlight.table.langitude': '纬度',

    'manage.popup.pleaseSelect': '请选择',
    'manage.popup.confirmDelete': '确认删除',
    'manage.popup.tips': '提示',
    'manage.popup.smartlight.addSmartlight': '新增智慧路灯',
    'manage.popup.smartlight.editSmartlight': '编辑智慧路灯',
    'manage.popup.smartlight.pole': '灯杆',
    'manage.popup.smartlight.screen': '显示屏',
    'manage.popup.smartlight.camera': '摄像头',
    'manage.popup.smartlight.rfid': 'RFID',
    'manage.popup.screen.addScreen': '新增显示屏',
    'manage.popup.screen.editScreen': '编辑显示屏',
    'manage.popup.screen.esn': 'ESN',
    'manage.popup.screen.name': '名称',
    'manage.popup.screen.domain': '域',

    'manage.playlist.time': '修改时间',
    'manage.playlist.add': '新增播放列表',
    'manage.playlist.browse': '选择文件',

    'manage.camera.ip': 'IP',
    'manage.camera.rtsp': 'RTSP端口',
    'manage.camera.http': 'HTTP端口',
    'manage.camera.username': '用户名',
    'manage.camera.password': '密码',
    'manage.camera.channel': '信道',
    'manage.camera.add': '新增摄像头',
    'manage.camera.edit': '编辑摄像头',

    'manage.rfid.esn': 'ESN',
    'manage.rfid.name': '名称',
    'manage.rfid.domain': '域',
    'manage.rfid.add': '新增RFID',
    'manage.rfid.edit': '编辑RFID',
  },
};