/**
 * Created by a on 2017/10/17.
 */
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

export const INIT_PROJECT = 'INIT_PROJECT';
export const INIT_PROGRAM_LIST = 'INIT_PROGRAM_LIST';
export const INIT_SCENE_LIST = 'INIT_SCENE_LIST';
export const INIT_ZONE_LIST = 'INIT_ZONE_LIST';
export const INIT_ITEM_LIST = 'INIT_ITEM_LIST';
export const LOCAL_UPDATE_ITEM_LIST = 'LOCAL_UPDATE_ITEM_LIST';
export const UPDATE_ITEM_LIST = 'UPDATE_ITEM_LIST';
export const UPDATE_ITEM_NAME = 'UPDATE_ITEM_NAME';
export const UPDATE_ITEM_SELECT = 'UPDATE_ITEM_SELECT';
export const UPDATE_ITEM_CANCEL = 'UPDATE_ITEM_CANCEL';
export const UPDATE_ITEM_EDIT = 'UPDATE_ITEM_EDIT';
export const UPDATE_ITEM_PREVIEW = 'UPDATE_ITEM_PREVIEW';
export const UPDATE_CUR_SCENE_ITEM = 'UPDATE_CUR_SCENE_ITEM';

export const INIT_CUR_TYPE = 'INIT_CUR_TYPE';
export const INIT_CURNODE = 'INIT_CURNODE';

export const UPDATE_TREE_JUDGE = 'UPDATE_TREE_JUDGE';
export const UPDATE_TREE_DATA = 'UPDATE_TREE_DATA';
export const UPDATE_TREE_LIST = 'UPDATE_TREE_LIST';
export const CLEAR_TREE_STATE = 'CLEAR_TREE_STATE';

export const ADD_ITEM_TO_SCENE = 'ADD_ITEM_TO_SCENE';