/**
 * Created by a on 2017/4/21.
 */
export const STARRIVER_LOGIN_SUCCESS = 'STARRIVER_LOGIN_SUCCESS';
export const STARRIVER_LOGIN_FAIL = 'STARRIVER_LOGIN_FAIL';
export const STARRIVER_LOGIN_CHANGE = 'STARRIVER_LOGIN_CHANGE';
export const STARRIVER_LOGIN_FOCUS = 'STARRIVER_LOGIN_FOCUS';