/**
 * Created by a on 2017/7/17.
 */
export const TREEVIEW_INIT = 'TREEVIEW_INIT'

export const TREEVIEW_TOGGLE = 'TREEVIEW_TOGGLE';
export const TREEVIEW_TOGGLE_ID = 'TREEVIEW_TOGGLE_ID';

export const TREEVIEW_MOVE = 'TREEVIEW_MOVE';
export const TREEVIEW_REMOVE = 'TREEVIEW_REMOVE';